# Generated by Django 3.2.9 on 2021-12-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodPlus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
    ]
