# Generated by Django 3.2.9 on 2021-12-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodPlus', '0002_auto_20211212_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='last_doantion',
            new_name='last_donation',
        ),
    ]
